version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.15.8

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install libtbb-dev libcrypto++6
      - run: go env -w GOPRIVATE=github.com/arcology-network
      - run: go build
      - store_artifacts:
          path: frontend-svc
